name = "2023-spring-game-jam"
default_targets = ["macos", "lovejs"]
build_directory = "makelove-build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-*/dist*",
]

[lovejs]
title = "2023 Spring Game Jam Game by Mike Purdy"

[macos]
# optionally, you can include a mac-specific icon, if not mac will use the same icon as other targets
#icon_file = "macIcon.png"  # or macIcon.icns

[macos.app_metadata]
CFBundleName = "2023 Spring Game Jam"
CFBundleIdentifier = "dev.mikepurdy.2023springgamejam"
NSHumanReadableCopyright = "Copyright © 2023 Mike Purdy"
CFBundleShortVersionString = "0.0.1"

